version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    network_mode: host
    shm_size: "2g"
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=120

  termin-bot:
    build:
      context: .
      dockerfile: Dockerfile_auto
    environment:
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    depends_on:
      - selenium
    network_mode: host
