name: Refresh AWS_CODEARTIFACT_AUTH_TOKEN

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/setup-aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install GitHub CLI (gh)
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Get New AWS_CODEARTIFACT_AUTH_TOKEN
        run: |
          export NEW_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain yilmaznaslan --domain-owner 250602908823 --region eu-central-1 --query authorizationToken --output text)
          echo "AWS_CODEARTIFACT_AUTH_TOKEN=$NEW_AUTH_TOKEN" >> $GITHUB_ENV

      - name: Update Secret
        run: |
          echo "Updating AWS_CODEARTIFACT_AUTH_TOKEN secret"
          echo "AWS_CODEARTIFACT_AUTH_TOKEN=$NEW_AUTH_TOKEN" | gh secret set AWS_CODEARTIFACT_AUTH_TOKEN -